---
- name: Clear Windows User Session
  hosts: Windows
  tasks:
    - name: Debug
      debug:
        msg: "Hello World"

    - name: Query User Session
      win_command: "query user"
      register: user_session
      ignore_errors: true

    - block:
        - name: Display User Session
          debug:
            msg: "{{ item.split(' ')[2] }}"
      loop: "{{ user_session.stdout_lines }}"