---
- name: Clear Windows User Session
  hosts: Windows
  tasks:
    - name: Debug
      debug:
        msg: "Hello World"

    - name: Query User Session
      win_shell: query user
      register: user_session

    - name: Display User Session
      debug:
        msg: "{{ user_session.stdout_lines }}"