---
- name: Clear Windows User Session
  hosts: Windows
  vars:
    proc: mobaxterm.exe
  tasks:
    - name: Query User Session
      win_command: "query process {{ proc }}"
      register: process
      ignore_errors: true

    - block:
        - name: Assert Query
          assert:
            that: process.stdout_lines != "" and process.stderr_lines == "No Process exists for mobaxterm.exe"
            fail_msg: "{{ process.stderr_lines }}"
            success_msg: "{{ process.stdout_lines }}"

        - name: Display process
          debug:
            msg: "{{ process.stdout_lines }}"

        - name: Terminate process
          win_command: "taskkill /F /IM mobaxterm.exe"
          ignore_errors: true

      rescue:
        - name: Process "{{ proc }}" not running
          debug:
            msg: "No Process exists for {{ proc }}"

        - meta: end_play



    # - name: Include clear_session.yml
    #   include_tasks: clear_session.yml
    #   loop: "{{ process.stdout_lines[1:] }}"