---
- name: Clear Windows User Session
  hosts: Windows
  tasks:
    - name: Debug
      debug:
        msg: "Hello World"

    - name: Query User Session
      win_command: "query user"
      register: user_session
      ignore_errors: true

    - name: Include clear_session.yml
      include_tasks: clear_session.yml
      loop: "{{ user_session.stdout_lines[1:] }}"